ntls-io/nautilus-wallet

- netlify.toml
> chore(web-client): add Netlify config

- web-client/.storybook/tsconfig.json
- web-client/src/app/app-routing.module.ts
- web-client/src/app/views/landing/landing.page.spec.ts
- web-client/src/app/views/login/login.page.spec.ts
- web-client/src/app/views/register/register.page.spec.ts
- web-client/src/app/views/wallet/wallet.page.spec.ts
- web-client/src/tests/test.helpers.ts
> test(web-client): add basic coverage for routes / navigation

- web-server/sgx-wallet-impl/src/lib.rs
- web-server/sgx-wallet-impl/src/ported/attestation.rs
- web-server/sgx-wallet-impl/src/ported/crypto.rs
- web-server/sgx-wallet-impl/src/ported/mod.rs
- web-server/sgx-wallet-test/enclave/Cargo.lock
- web-server/sgx-wallet-test/enclave/Cargo.toml
- web-server/sgx-wallet-test/enclave/src/lib.rs
- web-server/sgx-wallet-test/enclave/src/ported/mod.rs
- web-server/sgx-wallet-test/enclave/src/ported/proptest_crypto.rs
- web-server/sgx-wallet-test/enclave/src/ported/test_attestation.rs
- web-server/sgx-wallet-test/enclave/src/ported/test_crypto.rs
- Issue: #1
PRs:
- Follows #47
- Precedes #49
> feat(web-server): port crypto and attestation code

- web-server/sgx-wallet-impl/Cargo.lock
- web-server/sgx-wallet-impl/Cargo.toml
- web-server/sgx-wallet-impl/src/ported/kv_store/fs/mod.rs
- web-server/sgx-wallet-impl/src/ported/kv_store/fs/sgx_filer.rs
- web-server/sgx-wallet-impl/src/ported/kv_store/mod.rs
- web-server/sgx-wallet-impl/src/ported/mod.rs
- web-server/sgx-wallet-test/app/build.rs
- web-server/sgx-wallet-test/app/codegen/Enclave_u.c
- web-server/sgx-wallet-test/app/codegen/Enclave_u.h
- web-server/sgx-wallet-test/enclave/Cargo.lock
- web-server/sgx-wallet-test/enclave/Cargo.toml
- web-server/sgx-wallet-test/enclave/Enclave.edl
- web-server/sgx-wallet-test/enclave/Makefile
- web-server/sgx-wallet-test/enclave/codegen/Enclave_t.c
- web-server/sgx-wallet-test/enclave/codegen/Enclave_t.h
- web-server/sgx-wallet-test/enclave/src/helpers/mod.rs
- web-server/sgx-wallet-test/enclave/src/helpers/temp_dir.rs
- web-server/sgx-wallet-test/enclave/src/lib.rs
- web-server/sgx-wallet-test/enclave/src/ported/kv_store/tests.rs
- web-server/sgx-wallet-test/enclave/src/ported/mod.rs
- web-server/sgx-wallet-test/enclave/src/ported/test_kv_store.rs
- web-server/sgx-wallet-test/enclave/src/ported/test_kv_store_fs.rs
- Closes #4
PRs:
- Follows #48
- Precedes #67
> feat(web-server): port SGX KvStore code

- web-server/http-service-impl/Cargo.lock
- web-server/http-service-impl/Cargo.toml
- web-server/http-service-impl/src/server.rs
- web-server/sgx-wallet/app/Cargo.lock
> feat(web-server): add CORS headers

- .github/workflows/web-server-hw.yaml
(These were copied and changed from the SW-mode workflow in a rush, oops.)
> ci(web-server): fix HW-mode workflow

- asset-services/asset-services-api/src/handlers/misc.rs
- asset-services/asset-services-api/src/handlers/mod.rs
- asset-services/asset-services-api/src/main.rs
- asset-services/asset-services-celery/src/celery_box.rs
- asset-services/asset-services-celery/src/run_helpers.rs
- asset-services/asset-services-celery/src/tasks/misc.rs
- asset-services/asset-services-celery/src/tasks/mod.rs
- asset-services/asset-services-worker/src/main.rs
- Issue: #96 
- Follows #102 - Precedes #104
> refactor(asset-services-worker): small cleanups

- asset-services/.dockerignore
- asset-services/Cargo.lock
- asset-services/Cargo.toml
- asset-services/twilio-verify/Cargo.toml
- asset-services/twilio-verify/src/client.rs
- asset-services/twilio-verify/src/exports.rs
- asset-services/twilio-verify/src/lib.rs
- asset-services/twilio-verify/src/types.rs
- Issue: #96 
This adds a Rusty wrapper around `twilio-oai-verify-v2`.
- Follows #103 - Precedes #105
> feat(asset-services,twilio-verify): add twilio-verify client

- web-client/src/app/app-routing.module.ts
- web-client/src/app/components/action-item/action-item.component.html
- web-client/src/app/views/manual-address/manual-address-routing.module.ts
- web-client/src/app/views/manual-address/manual-address.module.ts
- web-client/src/app/views/manual-address/manual-address.page.html
- web-client/src/app/views/manual-address/manual-address.page.spec.ts
- web-client/src/app/views/manual-address/manual-address.page.stories.ts
- web-client/src/app/views/manual-address/manual-address.page.ts
- web-client/src/app/views/pay/pay.page.html
- web-client/src/app/views/send-funds/send-funds.page.html
- web-client/src/app/views/send-funds/send-funds.page.ts
- web-client/src/app/views/wallet-access/wallet-access.page.html
- web-client/src/global.scss
PR group:
- #111
- #112
- #113
- #114
- #71
> Demo branch part 4

- web-client/package.json
- web-client/src/app/components/header/header.component.html
- web-client/src/app/components/header/header.component.ts
- web-client/src/app/open-wallet.guard.ts
- web-client/src/app/services/enclave/index.ts
- web-client/src/app/services/wallet/index.ts
- web-client/src/app/services/wallet/wallet.service.ts
- web-client/src/app/stores/session/index.ts
- web-client/src/app/stores/session/session.query.ts
- web-client/src/app/stores/session/session.service.ts
- web-client/src/app/stores/session/session.store.ts
- web-client/src/app/views/login/login.page.spec.ts
- web-client/src/app/views/pay/pay.page.html
- web-client/src/app/views/pay/pay.page.ts
- web-client/src/app/views/print-wallet/print-wallet.page.html
- web-client/src/app/views/print-wallet/print-wallet.page.spec.ts
- web-client/src/app/views/print-wallet/print-wallet.page.stories.ts
- web-client/src/app/views/print-wallet/print-wallet.page.ts
- web-client/src/app/views/register/register.page.ts
- web-client/src/app/views/wallet-access/wallet-access.page.html
- web-client/src/app/views/wallet-access/wallet-access.page.ts
- web-client/src/app/views/wallet/wallet.page.html
- web-client/src/app/views/wallet/wallet.page.spec.ts
- web-client/src/app/views/wallet/wallet.page.ts
- web-client/src/tests/test.helpers.ts
We should pull out/refactor what is here into separate PRs so that we can have the flow implemented.
We also need to just go through the steps and go over the error handling where needed.
TODO:
TODO Refactor:
----
PR group:
- #111
- #112
- #113
- #114
- #71
> Demo branch part 5

- README.md
- web-client/README.md
- web-server/ARCHITECTURE.md
These could be expanded more, but it's a start.
> docs: add README files, ARCHITECTURE

- web-client/src/app/views/pay/pay.page.ts
Avoid sending 0 or more than available balance
Closes #140
> fix(web-client): validate payment amount

- web-client/src/app/views/landing/landing.page.ts
- https://github.com/ntls-io/nautilus-wallet/pull/170
> feat(web-client,LandingPage): make resetStores conditional on persistAkitaState

- web-client/src/app/components/pure-pay-page/pure-pay-page.component.html
- web-client/src/app/components/pure-pay-page/pure-pay-page.component.stories.ts
- web-client/src/app/components/pure-pay-page/pure-pay-page.component.ts
- web-client/src/app/services/algod.service.ts
- web-client/src/app/services/algosdk.utils.ts
- web-client/src/app/state/session-algorand.service.ts
- web-client/src/app/state/session.query.spec.ts
- web-client/src/app/state/session.query.ts
- web-client/src/app/state/session.store.ts
- web-client/src/app/utils/toast.helpers.ts
- web-client/src/app/views/pay/pay.page.html
- web-client/src/app/views/pay/pay.page.ts
- web-client/src/app/views/print-wallet/print-wallet.page.ts
- web-client/src/app/views/wallet/wallet.page.spec.ts
- web-client/src/app/views/wallet/wallet.page.ts
- web-client/src/environments/types.ts
- web-client/src/helpers/helpers.ts
- web-client/src/schema/algorand.helpers.spec.ts
- web-client/src/schema/algorand.helpers.ts
- web-client/src/tests/test.helpers.ts
- Issue: #92
- Follows https://github.com/ntls-io/nautilus-wallet/pull/173
- Precedes https://github.com/ntls-io/nautilus-wallet/pull/122
> feat(web-client): Algorand ASA support

- web-client/package-lock.json
- web-client/package.json
- web-client/patches/xrpl+2.2.1.patch
- web-client/src/app/services/xrpl.service.spec.ts
- web-client/src/app/services/xrpl.service.ts
- web-client/src/environments/environment.ts
- web-client/src/environments/types.ts
- web-client/src/polyfills.ts
- web-client/tsconfig.json
- Issue: #115
- Follows https://github.com/ntls-io/nautilus-wallet/pull/131
- Precedes https://github.com/ntls-io/nautilus-wallet/pull/184
> feat(web-client): add XRP service for signing and submitting transactions

- web-client/src/app/components/pay-amount-confirm/pay-amount-confirm.component.html
- web-client/src/app/components/pay-amount-confirm/pay-amount-confirm.component.stories.ts
- web-client/src/app/components/pay-amount-confirm/pay-amount-confirm.component.ts
- web-client/src/app/components/pay-amount-form/pay-amount-form.component.stories.ts
- web-client/src/app/components/pay/pay.component.html
- web-client/src/app/components/pay/pay.component.stories.ts
- web-client/src/app/components/pay/pay.component.ts
- web-client/src/app/components/pin-entry/pin-entry.component.stories.ts
- web-client/src/app/components/pure-pay-page/pure-pay-page.component.html
- web-client/src/app/components/pure-pay-page/pure-pay-page.component.stories.ts
- web-client/src/app/components/pure-pay-page/pure-pay-page.component.ts
- web-client/src/app/views/pay/pay.page.html
- web-client/src/app/views/pay/pay.page.stories.ts
- web-client/src/app/views/pay/pay.page.ts
This should fix the Chromatic stories that get inconsistently captured due to autofocus.
> test(web-client): propagate PayAmountFormComponent's autofocus input to parents

- web-client/src/app/components/pay/pay.component.stories.ts
2 seconds still seems to hit the timeout sometimes.
> test(web-client,PayPage): increase Storybook load timeout

- web-client/src/app/components/action-item/action-item.component.ts
- web-client/src/app/views/home/home.page.ts
- web-client/src/app/views/receive/receive.page.ts
- web-client/src/app/views/send-funds/send-funds.page.spec.ts
- web-client/src/app/views/send-funds/send-funds.page.ts
- web-client/src/app/views/wallet/wallet.page.ts
This is a small cleanup across a few components.
- Precedes https://github.com/ntls-io/nautilus-wallet/pull/191
> refactor(web-client): use common ActionItem type definition

- web-client/src/app/components/pure-wallet-page/pure-wallet-page.component.html
- web-client/src/app/components/pure-wallet-page/pure-wallet-page.component.spec.ts
- web-client/src/app/components/pure-wallet-page/pure-wallet-page.component.stories.ts
- web-client/src/app/components/pure-wallet-page/pure-wallet-page.component.ts
- web-client/src/app/components/pure-wallet-page/pure-wallet-page.module.ts
- web-client/src/app/views/wallet/wallet.module.ts
- web-client/src/app/views/wallet/wallet.page.html
- web-client/src/app/views/wallet/wallet.page.spec.ts
- web-client/src/app/views/wallet/wallet.page.ts
This makes the component presentation easier to work with and modify.
- Follows https://github.com/ntls-io/nautilus-wallet/pull/190
- Precedes https://github.com/ntls-io/nautilus-wallet/pull/193
> refactor(web-client): extract PureWalletPageComponent

- web-client/src/app/state/session.service.ts
This makes sure every session starts fresh.
> feat(web-client,SessionService): invariant: reset session store before open

- web-client/src/app/components/pay-amount-confirm/pay-amount-confirm.component.html
- web-client/src/app/components/pay-amount-confirm/pay-amount-confirm.component.stories.ts
- web-client/src/app/components/pay-amount-confirm/pay-amount-confirm.component.ts
- web-client/src/app/components/pay/pay.component.html
- web-client/src/app/components/pay/pay.component.stories.ts
- web-client/src/app/components/pay/pay.component.ts
- web-client/src/app/components/pure-pay-page/pure-pay-page.component.spec.ts
- web-client/src/app/components/pure-pay-page/pure-pay-page.component.ts
- web-client/src/app/utils/assets/assets.algo.asa.spec.ts
- web-client/src/app/utils/assets/assets.algo.spec.ts
- web-client/src/app/utils/assets/assets.algo.ts
- web-client/src/app/utils/assets/assets.config.spec.ts
- web-client/src/app/utils/assets/assets.config.ts
- web-client/src/app/utils/assets/assets.xrp.spec.ts
- web-client/src/app/utils/assets/assets.xrp.token.spec.ts
- web-client/src/app/utils/assets/assets.xrp.token.ts
- web-client/src/app/utils/assets/assets.xrp.ts
- web-client/src/app/views/pay/pay.page.html
- web-client/src/app/views/pay/pay.page.ts
- web-client/src/app/views/wallet/wallet.page.html
- web-client/src/app/views/wallet/wallet.page.stories.ts
- web-client/src/app/views/wallet/wallet.page.ts
- web-client/src/environments/types.ts
This adds more Onfido check status based UI.
- Follows https://github.com/ntls-io/nautilus-wallet/pull/193
> feat(web-client): Onfido-based soft limits

- web-client/package.json
This runs the same compodoc invocation as the Storybook / Angular builder, which is useful to refresh compodoc while developing stories.
> build(web-client): add storybook:compodoc command

- web-client/src/app/utils/console.helpers.ts
This improves the readability of logged exchanges.
> feat(web-client): better console logging helpers

- web-client/src/environments/environment.prod.ts
> chore(web-client): enable state persistence for demo deployment

- web-client/src/app/views/wallet/wallet.page.ts
Related to:
- #212
Closes: #212
> fix(web-client): prevent payments when the user has no balances

- web-client/src/app/components/header/header.component.html
- web-client/src/app/components/header/header.component.ts
> fix(web-client): clear stores on logout action

- web-client/src/app/components/balance-summary-card/balance-summary-card.component.html
Set the size of the item slot to accommodate bigger symbol so that amount
alignment stays consistent
> Fix balance alignment

- web-client/src/app/views/kyc/onfido-widget/onfido-widget.component.scss
> fix(web-client): onfido widget styling for phone number input

- web-client/src/app/components/balance-summary-card/balance-summary-card.component.html
- web-client/src/app/components/balance-summary-card/balance-summary-card.component.stories.ts
- web-client/src/app/components/balance-summary-card/balance-summary-card.component.ts
- web-client/src/app/components/pure-wallet-page/pure-wallet-page.component.html
- web-client/src/app/components/pure-wallet-page/pure-wallet-page.component.stories.ts
- web-client/src/app/components/pure-wallet-page/pure-wallet-page.component.ts
- web-client/src/app/views/wallet/wallet.page.html
- web-client/src/app/views/wallet/wallet.page.ts
Related to: [#220](https://github.com/ntls-io/nautilus-wallet/issues/220)
This is not a fix for the issue but it will give clarity on where and when the issue occurs, and if it is still an issue.
> feat(web-client): add loading indicator on the balance component

- web-client/capacitor.config.ts
- web-client/src/app/views/kyc/kyc.page.scss
Fix issue where country list on kyc page will disappear due device keyboard pushing it up
> fix(web-client): Remove kyc keyboard offset

- web-client/src/app/views/wallet-access/wallet-access.page.html
> fix(web-client): add close button to pin modal

- web-client/src/app/state/connector/connector.query.ts
- web-client/src/app/state/connector/connector.service.ts
- web-client/src/app/state/connector/connector.store.ts
- web-client/src/app/views/become-connector/become-connector.page.html
- web-client/src/app/views/become-connector/become-connector.page.spec.ts
- web-client/src/app/views/become-connector/become-connector.page.ts
Update state type to boolean.
Show success message after opt-in and navigate back
> perf(web-client): enhance connector opt-in process

- web-client/src/app/views/become-connector/become-connector.page.html
Justify the contents of the connector confirmation page
> style(web-client): justify connector confirmation checkbox

- web-client/src/app/state/connector/connector.query.ts
- web-client/src/app/state/connector/connector.service.ts
- web-client/src/app/state/connector/connector.store.ts
- web-client/src/app/views/become-connector/become-connector.page.html
- web-client/src/app/views/become-connector/become-connector.page.ts
update connector flow to store & retrieve walletId
> perf(web-client): set connector walletId

- web-client/package-lock.json
@jongbonga @IscoRuta98 Please note that you will need to update node to the correct version to prevent lockfile issues. Make sure that node is 16.15.1 and npm is 8.11.0
> chore(web-client): update node to 16.15.1 and npm to 8.11.0

- web-client/angular.json
- web-client/package.json
- web-client/src/environments/environment.demo.ts
- web-client/src/environments/environment.staging.ts
Creates new environment files for staging and demo.
> feat(web-client): update and add new deploy environments

- web-client/src/app/components/pure-wallet-page/pure-wallet-page.component.html
Hide connector option if user hasn't passed KYC
> perf(web-client): show connector only if KYCed

- web-client/src/app/state/session-xrpl.service.ts
- web-client/src/app/utils/assets/assets.common.spec.ts
- web-client/src/app/views/pay/pay.page.ts
- web-client/src/schema/actions.ts
> feat(web-client): implement asset commission calculation

- web-client/src/app/components/pay-amount-confirm/pay-amount-confirm.component.html
Fix for the [Copy Change Payment Page](https://app.clickup.com/t/2f9990k) bug.
> fix(web-client): Copy Change Payment Page

- web-client/src/app/components/pay-amount-form/pay-amount-form.component.ts
- web-client/src/app/pipes/transaction-fee.pipe.ts
- web-client/src/app/utils/assets/assets.common.ts
- web-client/src/environments/environment.demo.ts
- web-client/src/environments/environment.prod.ts
- web-client/src/environments/environment.staging.ts
- web-client/src/environments/environment.ts
- web-client/src/environments/types.ts
Update fee calculation (sum instead of substrat) & update max amount validation
> perf(web-client): update fee handling

- web-client/src/app/views/settings/settings.page.html
- web-client/src/app/views/settings/settings.page.ts
Update when should the connector option should show and hide.
If the device is a connector, the option will show if the connector wallet is the same as the user wallet.
it will hide is the connector wallet is different from the user wallet
the option will also show when the device is NOT a coonector to allow the user to become one
> refactor(web-client): update connector show logic

- web-client/angular.json
- web-client/package.json
- web-client/src/environments/environment.bhutan-demo.ts
Add configuration options for builds targeting the Bhutan demo environment `bhutan-demo`
> chore: add configuration for Bhutan demo

- web-client/src/environments/environment.bhutan-demo.ts
> fix: typo in Bhutan environment configuration

- web-client/src/environments/environment.bhutan-demo.ts
The Bhutan setup should use the new endpoint provided by Ripple
> fix(web-client): Bhutan environment endpoint

- web-server/sgx-wallet-impl/Cargo.lock
- web-server/sgx-wallet-impl/Cargo.toml
- web-server/sgx-wallet-impl/src/crypto/common.rs
- web-server/sgx-wallet-impl/src/crypto/key_agreement.rs
- web-server/sgx-wallet-impl/src/crypto/mod.rs
- web-server/sgx-wallet-impl/src/crypto/sgx_get_key.rs
- web-server/sgx-wallet-impl/src/lib.rs
- web-server/sgx-wallet-impl/src/ported/crypto.rs
Server-side functionality for #345
In the interest of time, unit/integration tests have been omitted.  This will have to be addressed as part of a separate pull request.
> feat: server-side Diffie-Hellman

- asset-services/Dockerfile
- asset-services/asset-services-api/Cargo.toml
- asset-services/asset-services-celery/Cargo.toml
- asset-services/asset-services-worker/Cargo.toml
- asset-services/onfido/Cargo.toml
- asset-services/rust-toolchain.toml
- asset-services/twilio-api/Cargo.toml
- asset-services/twilio-verify/Cargo.toml
Reverts ntls-io/nautilus-wallet#356
> Revert "build(asset-services): update Rust edition to 2021"

- web-server/sgx-wallet-impl/Cargo.toml
- web-server/sgx-wallet-impl/src/crypto/common.rs
- web-server/sgx-wallet-impl/src/crypto/key_agreement.rs
- web-server/sgx-wallet-impl/src/schema/actions.rs
- web-server/sgx-wallet-impl/src/schema/auth.rs
- web-server/sgx-wallet-impl/src/schema/session.rs
- web-server/sgx-wallet-impl/src/wallet_operations/dispatch.rs
- web-server/sgx-wallet-impl/src/wallet_operations/get_xrpl_wallet.rs
- web-server/sgx-wallet-impl/src/wallet_operations/mod.rs
- web-server/sgx-wallet-impl/src/wallet_operations/pin_reset.rs
- web-server/sgx-wallet-impl/src/wallet_operations/store.rs
- web-server/sgx-wallet-test/enclave/Cargo.toml
- web-server/sgx-wallet-test/enclave/src/lib.rs
- web-server/sgx-wallet-test/enclave/src/wallet_operations/mod.rs
- web-server/sgx-wallet-test/enclave/src/wallet_operations/test_get_xrpl_wallet.rs
- web-server/sgx-wallet/enclave/Cargo.toml
https://docs.google.com/document/d/1ni7n0RLirbTDDHtqZZ7KZLVDQVPUoZuznc__zQK3JLI/edit?pli=1
For Pull Payments, need an endpoint to request public key of XRPL wallet with wallet_id so that we can add it to the unsigned transaction before it gets sent to the enclave to get signed.
> feat(web-server): add get_xrpl_wallet operation

- web-client/src/app/services/enclave/enclave.service.spec.ts
- web-client/src/app/services/enclave/enclave.service.ts
- web-client/src/schema/actions.ts
Add `getXrplWallet` to enclave service.
This function will call https://github.com/ntls-io/nautilus-wallet/pull/360 backend function.
> feat(web-client): add getXrplWallet

- web-client/src/app/components/asset-accordion/asset-accordion.component.html
- web-client/src/app/components/asset-accordion/asset-accordion.component.ts
- web-client/src/environments/environment.bhutan-prod.ts
- web-client/src/environments/environment.bhutan-staging.ts
- web-client/src/environments/environment.palau-prod.ts
- web-client/src/environments/environment.palau-staging.ts
- web-client/src/environments/environment.prod.ts
- web-client/src/environments/environment.staging.ts
- web-client/src/environments/environment.ts
- web-client/src/environments/types.ts
https://app.clickup.com/t/2ya23rj
> feat(web-client): add tokenSymbol and tokenIssuer for pilots

- web-client/src/app/components/security-questions/security-questions.component.ts
Add apostrophe to pet's question
> style(web-client): fix typo on security questions

- web-client/src/app/views/kyc/onfido-widget/onfido-widget.component.scss
Fix issue where onfido background color doesn't match organisation theme
> fix(web-client): macth onfido country's bg color

- web-client/src/environments/environment.palau-prod.ts
In my previous PR, I mistakenely set the hideXrpBalance feature flag to false instead of true.
> fix(web-client): setting hideXrpBalance to true for palau production

- web-client/src/app/views/kyc/kyc.page.ts
KYC would hide country list on IOS, this PR resize the keyboard accordingly
> fix(web-client): fix keyboard on kyc

- web-client/src/app/state/session.query.ts
- web-client/src/app/views/wallet/wallet.page.html
Hide KYC if organisation is Bhutan
> feat(web-client): hide kyc for bhutan

- web-client/src/environments/environment.bhutan-prod.ts
- web-client/src/environments/environment.bhutan-staging.ts
- web-client/src/environments/environment.palau-prod.ts
- web-client/src/environments/environment.palau-staging.ts
- web-client/src/environments/environment.prod.ts
- web-client/src/environments/environment.staging.ts
[Change commission fee for pilots to 0%](https://app.clickup.com/t/30371qx)
> chore(environments): zero commission for pilots

- web-client/src/app/components/pure-pay-page/pure-pay-page.component.html
- web-client/src/app/components/pure-pay-page/pure-pay-page.component.ts
- web-client/src/app/components/pure-pay-page/pure-pay-page.module.ts
Clickup [Task](https://app.clickup.com/t/30tzf33)
**Bug**: Payment page showing nothing before user has opted into issued currency
Note: Assuming this PR is merged before the Autofund [Task](https://app.clickup.com/t/2y437jq), you need to fund a pilot's wallet with XRP using [this link](http://ripplerm.github.io/ripple-wallet/).
> fix(web-client): Fix Blank payment page

- web-client/package-lock.json
- web-client/package.json
- web-client/src/app/views/kyc/onfido-widget/onfido-widget.component.ts
Update for Onfido giving some bugs: `TypeError: cannot set property undefined (setting '__h')` so reverting the update
> fix(web-client): revert onfido dependency update

- web-client/package-lock.json
- web-client/package.json
- web-client/src/app/services/search.service.spec.ts
- web-client/src/app/services/search.service.ts
- web-client/src/app/state/session.service.ts
Adding search service to connect to the 2 backend APIs that connects to our CosmosDB. Also add wallet data into db when new wallet is created. Tested on ntls-staging.
> feat(web-client): add search service

- web-client/src/app/services/xrpl.service.ts
https://app.clickup.com/t/32ym6af
Adding destination tag to payments so that payments to accounts that require Destination Tag flags can occur.
> feat(web-client): add destination tag flag to payments

- web-client/src/environments/environment.bhutan-prod.ts
- web-client/src/environments/environment.bhutan-staging.ts
- web-client/src/environments/environment.palau-prod.ts
- web-client/src/environments/environment.palau-staging.ts
- web-client/src/environments/environment.prod.ts
- web-client/src/environments/environment.ts
Turn autofund off for ntls prod.
Set autofund amounts to 50.
> fix(web-client): set autofundXrpAmount to 50

- web-client/src/app/components/asset-accordion/asset-accordion.component.ts
Enable rippling for trustlines created so that wallets can transfer and interact with tokens between each other.
> feat(web-client): enable rippling for trustlines created

- web-client/src/app/views/receive/receive.page.html
- web-client/src/app/views/receive/receive.page.ts
> refactor(web-client): show receive address on receive page

- web-client/src/app/components/balance-summary-card/balance-summary-card.component.html
show retrieving balances text when loading or refreshing balances
> refactor(web-client): add retrieving balances text

- web-client/src/app/views/wallet/wallet.page.ts
- web-client/src/environments/environment.bhutan-prod.ts
- web-client/src/environments/environment.bhutan-staging.ts
- web-client/src/environments/environment.palau-prod.ts
- web-client/src/environments/environment.palau-staging.ts
- web-client/src/environments/environment.prod.ts
- web-client/src/environments/environment.staging.ts
- web-client/src/environments/environment.ts
- web-client/src/environments/types.ts
> feat(web-client): Pull payment flag

- web-client/src/app/views/wallet/wallet.page.ts
- web-client/src/environments/environment.bhutan-prod.ts
- web-client/src/environments/environment.bhutan-staging.ts
- web-client/src/environments/environment.palau-prod.ts
- web-client/src/environments/environment.palau-staging.ts
- web-client/src/environments/environment.prod.ts
- web-client/src/environments/environment.staging.ts
- web-client/src/environments/environment.ts
- web-client/src/environments/types.ts
Adding pull payment flag to rebuild apps.
* feat(web-client): Add hidePullPayment flag.
* style(web-client): run prettier
* fix(web-client): Fix ESLint error.
* style(web-client): run prettier
> feat(web-client): Pull payment flag (#486)

- web-client/src/app/components/pay-amount-form/pay-amount-form.component.html
- web-client/src/app/components/pay-amount-form/pay-amount-form.component.ts
- web-client/src/app/views/pull/pull.page.html
- web-client/src/app/views/pull/pull.page.ts
Pull Page minor fixes - change the following text:
Pay -> Pull
Money Sent! -> Payment received!
> fix(web-client): pull payment minor text fixes

- web-client/src/environments/environment.bhutan-prod.ts
- web-client/src/environments/environment.palau-prod.ts
- web-client/src/environments/environment.prod.ts
Update feature flags for auto-logout and pull payments.
> fix(web-client): update prod feature flags

- web-client/src/app/components/quick-access/quick-access.component.html
Clickup Task: [Fix Spelling Error.](https://app.clickup.com/t/31pm07a)
> fix(web-client): Fix spelling error.

- web-server/Dockerfile
Fix a typo in our `Dockerfile`
> fix(Dockerfile/typo): sed replace command

- web-server/sgx-wallet-impl/src/schema/actions.rs
- web-server/sgx-wallet-impl/src/schema/types.rs
Fix deserialization bug that's blocking PIN reset functionality
> fix(web-server): deserialize byte arrays

- web-server/sgx-wallet-impl/src/crypto/sgx_get_key.rs
- web-server/sgx-wallet-impl/src/schema/actions.rs
- web-server/sgx-wallet-impl/src/wallet_operations/pin_reset.rs
- web-server/sgx-wallet-test/enclave/src/lib.rs
- web-server/sgx-wallet-test/enclave/src/wallet_operations/mod.rs
- web-server/sgx-wallet-test/enclave/src/wallet_operations/test_pin_reset.rs
Simplified functionality, i.e. without cryptography.
> refactor(web-server): pin reset functionality

- web-client/src/app/components/pin-entry/pin-entry.component.html
- web-client/src/app/components/pin-entry/pin-entry.component.ts
- web-client/src/app/components/pin-entry/pin-entry.module.ts
- web-client/src/app/services/enclave/enclave.service.ts
- web-client/src/app/state/history/history.query.ts
- web-client/src/app/state/session.service.ts
- web-client/src/app/views/history/history.page.html
- web-client/src/app/views/history/history.page.ts
- web-client/src/app/views/pin-reset/pin-reset.module.ts
- web-client/src/app/views/pin-reset/pin-reset.page.html
- web-client/src/app/views/pin-reset/pin-reset.page.spec.ts
- web-client/src/app/views/pin-reset/pin-reset.page.ts
- web-client/src/app/views/wallet-access/wallet-access.page.html
- web-client/src/app/views/wallet/wallet.page.ts
- web-client/src/environments/environment.bhutan-prod.ts
- web-client/src/environments/environment.bhutan-staging.ts
- web-client/src/environments/environment.palau-prod.ts
- web-client/src/environments/environment.palau-staging.ts
- web-client/src/environments/environment.prod.ts
- web-client/src/environments/environment.staging.ts
- web-client/src/environments/environment.ts
- web-client/src/environments/types.ts
- web-client/src/schema/actions.ts
- web-client/src/schema/session.ts
Reverts ntls-io/nautilus-wallet#452
> Revert "feat(web-client): UI Pin Reset"

- web-client/src/environments/environment.bhutan-staging.ts
- web-client/src/environments/environment.palau-staging.ts
Enable the following features on Bhutan and Palau staging environments:
- Quick Access
- Pin Reset
- Auto logout
> refactor(web-client): Enable features on pilot staging.

- backend-services/src/data_service/operations/autofund.py
- backend-services/src/web_asgi/settings.py
- web-client/src/environments/environment.bhutan-prod.ts
- web-client/src/environments/environment.bhutan-staging.ts
- web-client/src/environments/environment.palau-prod.ts
- web-client/src/environments/environment.palau-staging.ts
- web-client/src/environments/environment.prod.ts
- web-client/src/environments/environment.staging.ts
- web-client/src/environments/environment.ts
- web-client/src/environments/types.ts
* chore (web-client): change autofund amount
* chore (web-client): revert autofund amount bhutan
* feat (backend-services): add autofund enpoint
* feat (backend-services): add autofund enpoint
* fix (backend-services): fix test conflict
* fix (backend-services): disable test for openssl ripemd legacy error
* fix (backend-services): fix ruff errors
* fix (backend-services): fix black errors
* fix (backend-services): fix black errors
* fix (backend-services): fix isort errors
* feat (web-client): add autofund api calls
* fix (web-client): run prettier
* fix (backend-service): fix api sender address bug.
* Add error handling to autofund, remove env variables.
* Run linting and format.
* Update backend-services/src/data_service/operations/autofund.py
* Update …
> chore: Autofund API Error handling (#537)

- web-client/src/app/components/security-questions/security-questions.component.html
- web-client/src/app/components/security-questions/security-questions.component.ts
- web-client/src/app/views/register/register.page.html
- web-client/src/app/views/register/register.page.ts
ClickUp Task: https://app.clickup.com/t/862jdc58n
> Submit bug fix

- backend-services/src/web_asgi/main.py
> fix(backend-services): Fix typo

- backend-services/src/data_service/operations/invite.py
- backend-services/tests/data_service/operations/test_invite.py
Backend corrections for the invite code functionality
> fix(backend-services): backend invite codes

- web-client/src/app/services/invite.service.ts
- web-client/src/app/views/register/register.page.ts
- web-client/src/environments/environment.bhutan-prod.ts
- web-client/src/environments/environment.bhutan-staging.ts
- web-client/src/environments/environment.palau-prod.ts
- web-client/src/environments/environment.palau-staging.ts
- web-client/src/environments/environment.prod.ts
- web-client/src/environments/environment.staging.ts
- web-client/src/environments/environment.ts
- web-client/src/environments/types.ts
Initial frontend functionality for invite codes
> feat(web-client): initial invite codes

- web-client/src/app/services/invite.service.ts
- web-client/src/app/views/register/register.page.ts
When an invalid code is used, there is no error message for the user. This PR fixes this issue by adding validation error message.
> Fix invite code bug

- backend-services/src/data_service/operations/invite.py
The aim of this PR is to add a checker in the case where an invite code has already been redeemed.
> refactor(backend): Include case where invite code is redeemed.

- web-client/src/app/components/pin-entry/pin-entry.component.html
> refactor(web-client): align remember address

- web-client/src/app/views/register/register.page.ts
The invite code pop up should be closeable with an exit button.
When closed it should not create an account.
Currently it is only closeable by pressing esc but an account is still created which is wrong.
> Invite Code | No exit button on the pop up

- web-client/package-lock.json
- web-client/package.json
- web-client/src/app/components/pin-entry/pin-entry.component.ts
- web-client/src/app/components/quick-access/quick-access.component.html
- web-client/src/app/components/quick-access/quick-access.component.ts
- web-client/src/app/state/qAccess/q-access.model.ts
- web-client/src/app/state/qAccess/q-access.query.ts
- web-client/src/app/state/qAccess/q-access.service.ts
- web-client/src/app/state/qAccess/q-access.store.ts
- web-client/src/app/views/two-factor-authentication/two-factor-authentication.page.html
- web-client/src/app/views/wallet-access/wallet-access.page.html
- web-client/src/app/views/wallet-access/wallet-access.page.ts
- web-client/src/environments/environment.ts
Refactor some of the logic in the store and removed unnecessary code
> refactor(web-client): remove address list if empty

- web-client/src/app/components/pay-from-to/pay-from-to.component.html
- web-client/src/app/components/pay-from-to/pay-from-to.component.ts
- web-client/src/app/views/pull/pull.page.html
- web-client/src/app/views/pull/pull.page.ts
Show receiver name on pay & sender name on pull if the address is found on the bookmark list
> feat(web-client): add bookmarked name to transactions

- web-client/package-lock.json
- web-client/package.json
- web-client/src/app/app.module.ts
- web-client/src/app/components/action-item/action-item.component.html
- web-client/src/app/components/action-item/action-item.component.ts
- web-client/src/app/modules/shared/shared.module.ts
- web-client/src/app/utils/camara.helpers.ts
- web-client/src/app/views/delete-user/delete-user.page.html
- web-client/src/app/views/delete-user/delete-user.page.ts
- web-client/src/app/views/send-funds/send-funds.page.html
- web-client/src/app/views/send-funds/send-funds.page.ts
- web-client/src/app/views/transfer-funds/transfer-funds.page.html
- web-client/src/app/views/transfer-funds/transfer-funds.page.ts
- web-client/src/app/views/wallet-access/wallet-access.page.ts
This update will correctly show or hide the qr code access button
> refactor(web-client): check if device has camera

- web-client/src/app/services/enclave/enclave.service.spec.ts
- web-client/src/app/state/session.query.spec.ts
- web-client/src/app/views/print-wallet/print-wallet.page.spec.ts
- web-client/src/schema/entities.ts
- web-client/src/tests/state.helpers.spec.ts
- web-client/src/tests/state.helpers.ts
- web-server/sgx-wallet-impl/src/schema/entities.rs
Aim of this PR is to assist with debugging [Forgot Pin ,Accepting incorrect security questions](https://ntls.atlassian.net/jira/software/projects/NW/boards/1?selectedIssue=NW-198) bug.
> refactor(web-server): Return auth map within WalletDisplay

- web-client/package-lock.json
- web-client/package.json
- web-client/src/app/state/setup/setup.service.ts
- web-client/src/app/views/landing/landing.page.ts
On native devices, it will check new version and prompt (force) users to update their app
> feat(web-client): check & prompt user for update

- web-client/src/app/services/enclave/enclave.service.spec.ts
- web-client/src/app/state/session.query.spec.ts
- web-client/src/app/views/print-wallet/print-wallet.page.spec.ts
- web-client/src/schema/entities.ts
- web-client/src/tests/state.helpers.spec.ts
- web-client/src/tests/state.helpers.ts
- web-server/sgx-wallet-impl/src/schema/entities.rs
Reverts ntls-io/nautilus-wallet#577
> Revert "refactor(web-server): Return auth map within WalletDisplay"

- web-client/src/app/views/wallet/wallet.page.ts
This addresses the issue where the tx history will not display the name because there bookmark list isn't available yet
> fix(web-client): pull bookmarks when wallet opens

- web-client/src/app/state/session-xrpl.service.ts
- web-client/src/app/utils/errors/global-error-handler.ts
- web-client/src/app/views/pull/pull.page.ts
- web-client/src/environments/environment.ts
This PR aims to fix the following bug: [Prevent auto-logout when an error occurs](https://ntls.atlassian.net/jira/software/projects/NW/boards/1?selectedIssue=NW-178).
> fix(web-client): Prevent auto-logout

- web-client/src/app/views/manual-address/manual-address.page.html
- web-client/src/app/views/manual-address/manual-address.page.ts
- web-client/src/app/views/transfer-funds/transfer-funds.page.ts
The aim of this PR is to address the following issue: [Pull Payment - Enter Wallet Address Textbox Naming](https://ntls.atlassian.net/jira/software/projects/NW/boards/1?selectedIssue=NW-202).
> fix(web-client): Pull Payment - Enter Wallet Address Textbox Naming

- web-server/sgx-wallet-impl/src/schema/auth.rs
- web-server/sgx-wallet-impl/src/schema/entities.rs
This PR aims to fix to the following issue: [Forgot Pin | Accepting incorrect security questions](https://ntls.atlassian.net/jira/software/projects/NW/boards/1/backlog?selectedIssue=NW-198).
> fix(web-server): Fix backend Pin Reset accepting any security answers.

- backend-services/README.md
Updating README with code formatting command for backend-services.
> docs(backend-services): add code format section for black and isort

- web-server/sgx-wallet-impl/src/schema/auth.rs
- web-server/sgx-wallet-impl/src/schema/entities.rs
Reverts ntls-io/nautilus-wallet#589
> Revert "fix(web-server): Fix backend Pin Reset accepting any security answers."

- web-server/sgx-wallet-impl/src/schema/auth.rs
- web-server/sgx-wallet-test/enclave/src/helpers/wallet_store.rs
- web-server/sgx-wallet-test/enclave/src/lib.rs
- web-server/sgx-wallet-test/enclave/src/wallet_operations/test_pin_reset.rs
Fix for the following issue: [Forgot Pin | Accepting incorrect security questions](https://ntls.atlassian.net/jira/software/projects/NW/boards/1?selectedIssue=NW-198)
> fix(web-server): check for empty store in auth method.

- backend-services/README.md
Our github workflows also runs `poetry run ruff` so adding it to the docs.
> docs: update README with ruff command

- web-client/src/app/components/new-schedule-pay/new-schedule-pay.component.html
- web-client/src/app/components/new-schedule-pay/new-schedule-pay.component.ts
- web-client/src/app/state/recurring-pay/recurring-pay.service.ts
- web-client/src/app/utils/notification/swal-helper.ts
- web-client/src/app/views/recurring-pay/recurring-pay.page.html
- web-client/src/app/views/schedule-pay/schedule-pay.page.ts
- web-client/src/global.scss
This PR aims to change the following for Recurring Payment feature:
-  Frequency should be an option between:
Every Day
Every Week
Every Month
Quarterly
- After successful schedule, return to the main recurring payments page.
- Date picker icon should be white.
> fix-recurring-pay-frontend

- web-client/src/app/views/transfer-funds/transfer-funds.page.ts
Jira ticket - https://ntls.atlassian.net/jira/software/projects/NW/boards/1?assignee=621880712d1a9d0069968d6b&selectedIssue=NW-204
Fix search functionality regression.
What happened:
Feature was added in these PRs:
* https://github.com/ntls-io/nautilus-wallet/pull/426/files#diff-d61683c95ca28000d1e08b27aeeb5745f742fb8b41797a0430ae49aea082b9aa
* https://github.com/ntls-io/nautilus-wallet/pull/434
Then we added pull payment:
Jonathan refactored the code so that we can use same code for both pull and pay and left out the search functionality.
> fix(web-client): add search functionality to transfer-funds page

- web-client/src/environments/environment.palau-prod.ts
Use non-standard port as some networks blocks this.
> chore: change palau prod port to 443

- web-client/src/app/utils/notification/swal-helper.ts
- web-client/src/app/views/pay/pay.page.ts
- web-client/src/app/views/pull/pull.page.ts
- web-client/src/app/views/transfer-funds/transfer-funds.page.ts
Aim of this PR is to improve error messages for Pull payments, according to the below: (Related to [Issuw NW-107](https://ntls.atlassian.net/jira/software/projects/NW/boards/1?selectedIssue=NW-107))
Pulling Money from your own wallet
- Error Message not user friendly
Pulling Money from Empty Wallet
- Error Message not friendly
Pull payment Enter invalid Wallet Address
- Not getting expected Result. User is able to enter invalid wallet address and run through the whole process only to get Error Occurred error message
> fix(web-client): Improve error msg for pull pay

- web-client/src/app/components/new-schedule-pay/new-schedule-pay.component.html
- web-client/src/app/components/new-schedule-pay/new-schedule-pay.component.scss
- web-client/src/app/views/schedule-pay/schedule-pay.page.ts
This PR aims to fix the following tickets:
- [NW-217: UI: Recurring Payment - Set Schedule - Dropdown](https://ntls.atlassian.net/jira/software/projects/NW/boards/1?selectedIssue=NW-217)
- [NW-218: Back Button on Recurring Payments Screen (After Creating Recurring Payment)](https://ntls.atlassian.net/jira/software/projects/NW/boards/1?selectedIssue=NW-218)
> fix-recurring-pay

- README.md
- docs/book/src/SUMMARY.md
- docs/book/src/design/backend-services.md
- docs/book/src/design/overview.md
- docs/book/src/design/wallet-connector-app.md
- docs/book/src/design/wallet-tee.md
- docs/book/src/nautilus-wallet.md
Aim: Update Nautilus Wallet Documentation.
> refactor(book): update documentation

- README.md
> fix(book): Fix minor typos
