- .github/workflows/web-client.yaml
This avoids running the web-client actions on pushes and PRs that don't touch the web-client code.
> ci(web-client): limit action triggering by path

- web-client/package-lock.json
- web-client/package.json
- web-client/src/app/views/wallet/wallet.module.ts
- web-client/src/app/views/wallet/wallet.page.html
- web-client/src/app/views/wallet/wallet.page.stories.ts
> Display QR-Code

- web-client/src/stories/theme.html
- web-client/src/stories/theme.stories.ts
- From #28
This story gives us a quick view of how the Nautilus brand palette maps to the Ionic theme.
(This could also be a starting point for a [design system](https://storybook.js.org/tutorials/design-systems-for-developers/) for the Nautilus brand.)
> test(web-client): add story for the Ionic theme

- .github/workflows/web-client.yaml
- web-client/e2e/protractor.conf.js
This should avoid the e2e tests breaking whenever the GitHub Actions
virtual environment lags behind the latest Chrome major version release.
> ci(web-client): disable ng e2e's webdriverUpdate behaviour for GitHub Actions

- web-client/src/test.ts
- web-client/tsconfig.spec.json
This works around upstream Angular issue:
https://github.com/angular/angular-cli/issues/1735
This will decrease the reported coverage percentage, but the adjusted number should actually be correct now.
> test(web-client): fix coverage reporting

- web-client/src/app/views/home/home.page.spec.ts
- web-client/src/app/views/landing/landing.page.spec.ts
- web-client/src/app/views/login/login.page.spec.ts
- web-client/src/app/views/register/register.page.spec.ts
- web-client/src/app/views/send-funds/send-funds.page.spec.ts
- web-client/src/app/views/wallet/wallet.page.spec.ts
- web-client/src/tests/test.helpers.ts
- web-client/src/tests/transloco.helpers.ts
- web-client/tsconfig.spec.json
- Follows #39
- See also #36 for more context
This should make the page tests more reliable by adding an initial router navigation, and fixes two issues that were non-deterministic failures before:
- Remove component declarations from test modules. (These conflict with the code under test, and cause the tests to fail once the code under test is fully loaded.)
- Add import for Transloco, required by the landing page
> test(web-client): better page route tests

- web-client/src/app/views/lockscreen/lockscreen.page.html
This was causing the focus ring to render out of alignment.
(This showed up in Chromatic intermittently because of a snapshot / `autofocus` race, I'm guessing.)
- Precedes #65
> fix(web-client): remove clearInput button from lock screen PIN input

- .github/workflows/web-client.yaml
Remove the path conditions, for now, so that this builds even for server-only changes.
This simplifies our checks, for now, and will probably be needed for full client / server integration tests later.
> ci(web-client): always run GitHub Actions

- web-client/src/app/views/lockscreen/lockscreen.page.html
- web-client/src/app/views/lockscreen/lockscreen.page.stories.ts
- web-client/src/app/views/lockscreen/lockscreen.page.ts
This exposes LockscreenPage's `autofocus` as an input property, preserving the default `true`, but disabling it for Storybook.
This should avoid the inconsistent snapshots in Chromatic.
> test(web-client, LockscreenPage): default autofocus to false, for Chromatic

- web-client/.eslintrc.json
- web-client/angular.json
- web-client/package-lock.json
- web-client/package.json
- web-client/proxy.conf.json
- web-client/src/app/services/algosdk.utils.ts
- web-client/src/app/services/wallet.service.spec.ts
- web-client/src/app/services/wallet.service.ts
- web-client/src/environments/environment.prod.ts
- web-client/src/environments/environment.ts
- web-client/src/schema/actions.ts
- web-client/src/schema/algorand.helpers.spec.ts
- web-client/src/schema/algorand.helpers.ts
- web-client/src/schema/attestation.ts
- web-client/src/schema/crypto.ts
- web-client/src/schema/entities.ts
- web-client/src/schema/msgpack.ts
- web-client/src/schema/sealing.ts
- web-client/src/schema/types.ts
- web-client/src/tests/test.helpers.ts
- web-client/tsconfig.json
Issues:
- #25
- #26
- #27
- ~Use https://github.com/capacitor-community/http for http calls~ – the library does not support posting binary data, it seems: we'll need upstream patches.
- WalletService test coverage: split to #74
- Schema test coverage: split to #75
- #66 (for Chromatic baseline fix)
- #65 (for `package-lock.json` sync)
> feat(web-client): add API schema and service

- web-server/sgx-wallet-test/app/codegen/Enclave_u.c
- web-server/sgx-wallet-test/app/codegen/Enclave_u.h
- web-server/sgx-wallet-test/app/codegen/Enclave_u.rs
- web-server/sgx-wallet-test/app/src/main.rs
- web-server/sgx-wallet-test/app/src/safe_ecalls.rs
- web-server/sgx-wallet-test/enclave/Enclave.edl
- web-server/sgx-wallet-test/enclave/codegen/Enclave_t.c
- web-server/sgx-wallet-test/enclave/codegen/Enclave_t.h
- web-server/sgx-wallet-test/enclave/src/lib.rs
* wrap `enclave_u::run_tests_ecall` in `safe_run_tests_ecall`
* return failed test count from `run_tests_ecall`
* exit with error status from `main` if any tests failed
> test(web-server, sgx-wallet-test): exit with error status if tests failed

- web-server/Dockerfile
- web-server/rust-toolchain.toml
This is needed for semver, which depends on stable `feature(nonzero_leading_trailing_zeros)` (Rust 1.53).
See also: https://github.com/registreerocks/nautilus-wallet/wiki/Rust-SGX-SDK-toolchain-support-status
> build(web-server): update Rust nightly toolchain: 2021-03-25 → 2021-05-10

- asset-services/Cargo.lock
- asset-services/asset-services-api/Cargo.toml
- asset-services/asset-services-api/src/helpers.rs
- asset-services/asset-services-celery/Cargo.toml
- asset-services/asset-services-celery/src/run_helpers.rs
- web-server/sgx-wallet/app/Cargo.lock
- web-server/sgx-wallet/app/Cargo.toml
- web-server/sgx-wallet/app/src/main.rs
- Issue: #96 
This was originally an internal crate, but that's trickier for Docker to share, so the simplest way forward seems to be to just go ahead and split it out fully.
- Precedes: #103
> refactor: split out env-var-helpers library

- asset-services/Cargo.lock
- asset-services/Cargo.toml
- asset-services/asset-services-api/Cargo.toml
This fixes the build: GitHub's no longer serving the old revision.
> fix(asset-services): update to tower-http 0.1.2 for CORS support

- web-client/src/environments/environment.ts
- web-client/src/environments/types.ts
- web-client/src/main.ts
This adds an environment option to enable persistent sessions, which makes development much nicer.
This enables persistence for development by default, but leaves it disabled for production.
> feat(web-client): support Akita state persistence

- web-client/src/app/components/balance-summary-card/balance-summary-card.component.html
- web-client/src/app/components/balance-summary-card/balance-summary-card.component.spec.ts
- web-client/src/app/components/balance-summary-card/balance-summary-card.component.stories.ts
- web-client/src/app/components/balance-summary-card/balance-summary-card.component.ts
- web-client/src/app/components/balance-summary-card/balance-summary-card.module.ts
- web-client/src/app/components/header/header.component.html
- web-client/src/app/pipes/asset-amount.pipe.spec.ts
- web-client/src/app/pipes/asset-amount.pipe.ts
- web-client/src/app/pipes/asset-pipes.module.ts
- web-client/src/app/pipes/asset-symbol.pipe.spec.ts
- web-client/src/app/pipes/asset-symbol.pipe.ts
- web-client/src/app/utils/asset.display.spec.ts
- web-client/src/app/utils/asset.display.ts
- web-client/src/app/views/wallet/wallet.module.ts
- web-client/src/app/views/wallet/wallet.page.html
- web-client/src/app/views/wallet/wallet.page.spec.ts
- web-client/src/app/views/wallet/wallet.page.stories.ts
- web-client/src/app/views/wallet/wallet.page.ts
This adds a basic balance summary and refresh button to the wallet page.
- Follows https://github.com/ntls-io/nautilus-wallet/pull/167
- Precedes https://github.com/ntls-io/nautilus-wallet/pull/169
> feat(web-client): balance summary & refresh button

- web-client/src/app/services/enclave/enclave.service.spec.ts
- web-client/src/app/state/session-algorand.service.ts
- web-client/src/app/state/session.query.spec.ts
- web-client/src/app/views/pay/pay.page.stories.ts
- web-client/src/app/views/print-wallet/print-wallet.page.spec.ts
- web-client/src/schema/actions.ts
- web-client/src/schema/entities.ts
- web-client/src/schema/types.ts
- web-client/src/tests/state.helpers.spec.ts
- web-client/src/tests/state.helpers.ts
- web-server/sgx-wallet-impl/Cargo.lock
- web-server/sgx-wallet-impl/Cargo.toml
- web-server/sgx-wallet-impl/src/schema/actions.rs
- web-server/sgx-wallet-impl/src/schema/entities.rs
- web-server/sgx-wallet-impl/src/schema/types.rs
- web-server/sgx-wallet-impl/src/wallet_operations/create_wallet.rs
- web-server/sgx-wallet-impl/src/wallet_operations/mod.rs
- web-server/sgx-wallet-impl/src/wallet_operations/sign_transaction.rs
- web-server/sgx-wallet-impl/src/wallet_operations/sign_transaction_xrpl.rs
- web-server/sgx-wallet-impl/src/wallet_operations/store.rs
- web-server/sgx-wallet-test/enclave/Cargo.lock
- web-server/sgx-wallet-test/enclave/Cargo.toml
- web-server/sgx-wallet-test/enclave/src/lib.rs
- web-server/sgx-wallet-test/enclave/src/schema/mod.rs
- web-server/sgx-wallet-test/enclave/src/schema/test_types.rs
- web-server/sgx-wallet-test/enclave/src/wallet_operations/mod.rs
- web-server/sgx-wallet-test/enclave/src/wallet_operations/test_create_wallet.rs
- web-server/sgx-wallet-test/enclave/src/wallet_operations/test_dispatch.rs
- web-server/sgx-wallet-test/enclave/src/wallet_operations/test_sign_transaction_xrpl.rs
- web-server/sgx-wallet/enclave/Cargo.lock
This adds XRPL support to the `web-server` enclave, and corresponding representation types to the `web-client` schema.
Note that this branch currently switches from doubling the Algorand account as the wallet ID to doubling the XRPL account as wallet ID: see `key_from_id`. We should file a follow-up issue to address this.
- Issue: https://github.com/ntls-io/nautilus-wallet/issues/115
- Follows https://github.com/ntls-io/nautilus-wallet/pull/179
- Precedes https://github.com/ntls-io/nautilus-wallet/pull/169
> feat: add enclave XRPL support

- web-client/src/app/views/scanner/scanner.page.spec.ts
We're currently having to retry a lot of CI jobs due to this.
> test(web-client): disable flaky ScannerPage test

- web-client/src/app/state/session-algorand.service.spec.ts
- web-client/src/app/state/session-algorand.service.ts
- web-client/src/app/state/session.service.ts
- Factor out `SessionService.signTransaction` from `SessionAlgorandService.sendTransaction`
- Make `SessionAlgorandService` depend on `SessionService`, rather than the other way around
- Follows https://github.com/ntls-io/nautilus-wallet/pull/122
- Precedes https://github.com/ntls-io/nautilus-wallet/pull/185
> refactor(web-client): session services transaction signing

- web-client/src/app/components/pay/pay.component.stories.ts
4s still managed to hit a timeout: hopefully 8s is better.
This also uses the timeout for the Chromatic snapshot delay, to avoid unreliable snapshots.
- https://github.com/ntls-io/nautilus-wallet/pull/181
> test(web-client,PayComponent): bump Storybook load timeout again

- web-client/.storybook/preview.js
- web-client/package-lock.json
- web-client/package.json
- web-client/src/app/services/xrpl.utils.spec.ts
- web-client/src/app/services/xrpl.utils.ts
- web-client/src/app/state/session-xrpl.service.spec.ts
- web-client/src/app/state/session-xrpl.service.ts
- web-client/src/app/state/session.query.spec.ts
- web-client/src/app/state/session.query.ts
- web-client/src/app/state/session.store.ts
- web-client/src/app/utils/assets/assets.xrp.spec.ts
- web-client/src/app/utils/assets/assets.xrp.token.spec.ts
- web-client/src/app/utils/assets/assets.xrp.token.ts
- web-client/src/app/utils/assets/assets.xrp.ts
This adds:
- `SessionState` fields: `xrplAccountRoot`, `xrplBalances`
- `SessionQuery` observables: `xrplBalances`, `allBalances`
- `SessionXrplService`, with operations: `loadAccountData`, `sendFunds`
along with supporting code:
- `xrpl.utils` (XRPL transaction signing helpers)
- `assets.xrp` & `assets.xrp.token` (asset amount representation helpers for XRP and XRPL tokens)
- Follows https://github.com/ntls-io/nautilus-wallet/pull/184
- Precedes https://github.com/ntls-io/nautilus-wallet/pull/187
> feat(web-client): add XRPL session state and SessionXrplService

- web-client/src/app/components/pure-pay-page/pure-pay-page.component.ts
- web-client/src/app/services/xrpl.utils.ts
- web-client/src/app/state/session-xrpl.service.ts
- web-client/src/app/state/session.service.ts
- web-client/src/app/utils/console.helpers.ts
- web-client/src/app/views/manual-address/manual-address.page.ts
- web-client/src/app/views/pay/pay.page.html
- web-client/src/app/views/pay/pay.page.ts
- web-client/src/app/views/wallet/wallet.page.ts
Summary:
- `PayPage` (and components): Handle sending XRP & XRPL tokens.
- `WalletPage`: Show XRP & XRPL token balances.
- `xrpl.utils`: Add transaction status helpers.
- `console.helpers`: Helpers for more useful and readable console logging, especially of important API exchanges.
- Follows https://github.com/ntls-io/nautilus-wallet/pull/185
> feat(web-client): add XRP & XRPL tokens to Pay & Wallet pages

- web-server/sgx-wallet-impl/Cargo.lock
- web-server/sgx-wallet-impl/Cargo.toml
- web-server/sgx-wallet-impl/src/schema/actions.rs
- web-server/sgx-wallet-impl/src/wallet_operations/open_wallet.rs
- web-server/sgx-wallet-impl/src/wallet_operations/sign_transaction.rs
- web-server/sgx-wallet-impl/src/wallet_operations/store.rs
- web-server/sgx-wallet-test/enclave/Cargo.lock
- web-server/sgx-wallet-test/enclave/src/lib.rs
- web-server/sgx-wallet-test/enclave/src/wallet_operations/mod.rs
- web-server/sgx-wallet-test/enclave/src/wallet_operations/test_store.rs
- web-server/sgx-wallet/enclave/Cargo.lock
- Add `sgx_trts` dependency
- Factor out common `unlock_wallet` helper from `open_wallet` and `sign_transaction`
- Replace PIN comparison with [ConsttimeMemEq]
[ConsttimeMemEq]: https://dingelish.github.io/sgx_trts/sgx_trts/memeq/trait.ConsttimeMemEq.html
- Precedes https://github.com/ntls-io/nautilus-wallet/pull/189
> refactor(web-server): add unlock_wallet helper, with constant-time compare

- web-client/src/app/services/enclave/enclave.service.ts
- web-client/src/app/state/session.query.spec.ts
- web-client/src/app/state/session.query.ts
- web-client/src/app/state/session.service.ts
- web-client/src/app/state/session.store.ts
- web-client/src/app/views/kyc/kyc.page.html
- web-client/src/app/views/kyc/kyc.page.scss
- web-client/src/app/views/kyc/kyc.page.spec.ts
- web-client/src/app/views/kyc/kyc.page.stories.ts
- web-client/src/app/views/kyc/kyc.page.ts
- web-client/src/schema/actions.ts
Summary:
- Add client-side support for Onfido check storage: https://github.com/ntls-io/nautilus-wallet/pull/189
- Improve `KycPage` UI/UX, and allow saving successful results.
- Follows https://github.com/ntls-io/nautilus-wallet/pull/191
- Precedes https://github.com/ntls-io/nautilus-wallet/pull/194
> feat(web-client,KycPage): use Onfido check storage

- web-client/src/app/services/xrpl.service.ts
- web-client/src/app/state/session-xrpl.service.ts
- web-client/src/app/state/session.query.spec.ts
- web-client/src/app/state/session.query.ts
- web-client/src/app/state/session.store.ts
- web-client/src/app/views/wallet/wallet.page.ts
This performs opportunistic XRPL token opt-in to any peer trustlines on wallet open (similar to the Algorand ASA opt-in).
This needs more proper UI at some point, but this is a minimal foundation to enable basic XRPL token transacting.
> feat(web-client): add opportunistic XRPL token opt-ins

- web-client/src/app/services/xrpl.service.ts
- web-client/src/app/services/xrpl.utils.spec.ts
- web-client/src/app/services/xrpl.utils.ts
- web-client/src/app/state/session-xrpl.service.ts
- web-client/src/app/views/wallet/wallet.page.ts
This handles the initial empty XRPL account state gracefully, rather than crashing.
> feat(web-client): handle XRPL `actNotFound`

- web-client/src/app/services/messaging.service.spec.ts
- web-client/src/app/services/messaging.service.ts
- web-client/src/app/services/nautilus-asset-services.service.spec.ts
- web-client/src/app/services/nautilus-asset-services.service.ts
- web-client/src/app/services/onfido.service.ts
- web-client/src/app/state/session.service.ts
- web-client/src/app/views/register/register.page.ts
Summary:
- Factor out `NautilusAssetServicesService`
- Add `MessagingService`
- Send SMS after `SessionService.saveOnfidoCheck`
- Uses functionality from https://github.com/ntls-io/nautilus-wallet/pull/201 
- Follows https://github.com/ntls-io/nautilus-wallet/pull/202
> feat(web-client): add SMS messaging

- web-client/src/app/services/xrpl.service.ts
- web-client/src/app/views/wallet/wallet.page.spec.ts
- web-client/src/app/views/wallet/wallet.page.ts
- web-client/src/environments/environment.prod.ts
- web-client/src/environments/environment.ts
- This should resolve https://github.com/ntls-io/nautilus-wallet/issues/196
Summary:
- Refresh the wallet on open, not just on "Refresh" button click
- Fix overlapping state crash in `XrplClient`: this could be triggered by refreshing while a refresh was still in progress
- Increase the default XRPL client connection timeout from 5s to 20s, to avoid semi-frequent intermittent timeout errors
> feat(web-client): better wallet refresh

- web-client/src/app/state/session.query.ts
- web-client/src/app/views/wallet/wallet.page.ts
- web-client/src/helpers/helpers.spec.ts
- web-client/src/helpers/helpers.ts
- Remove the "Deposit some Algo to get started" message for empty wallets
- Skip showing a zero Algo balance (particularly for fresh / empty / non-Algo wallets)
> feat(web-client): streamline Algorand UI

- web-client/src/app/components/balance-summary-card/balance-summary-card.component.html
- web-client/src/app/components/balance-summary-card/balance-summary-card.component.ts
A message that indicates that there are no assets when opening wallet for the first time.
Related to:
[217](https://github.com/ntls-io/nautilus-wallet/issues/217)
> chore(web-client): Enable a message to let user know there are no assets #217

- web-client/package-lock.json
- web-client/package.json
- web-client/src/app/views/register/register.module.ts
- web-client/src/app/views/register/register.page.html
- web-client/src/app/views/register/register.page.spec.ts
- web-client/src/app/views/register/register.page.stories.ts
- web-client/src/app/views/register/register.page.ts
- Remove validation underlines on inputs.
- Validation was ignored after the pin was entered, highlighted then deleted.
- It also addresses the case where confirm pin does not validate after the match happened but the pin is deleted after.
- Add `minlength` for FirstName & LastName
> fix(web-client): Fix register UI & Pin validation

- web-client/src/theme/variables.scss
The current shade of red on blue is hard to read, especially for colour
blindness. The error color has been changed to comply with AA version of
WCAG.
> chore(web-client): Error color contrast is hard to read

- web-client/src/app/state/session-xrpl.service.ts
- web-client/src/app/views/delete-user/delete-user.page.html
Magically fixes the delete feature ;) 
https://app.clickup.com/t/2b0107c
1. Nautilus Issuer (FOO) creates Trustline with Wallet A with limit 1000
2. Wallet A matches Trustline `limit_peer` to 1000 so that it can receive FOO - https://github.com/ntls-io/nautilus-wallet/blob/dc4e1ac4f801ac196f8269d33bf25c4efae15706/web-client/src/app/state/session-xrpl.service.ts#L287
Now if we want to delete Wallet A account, we need to remove Trustline
3. Nautilus Issuer (FOO) defaults Trustline with Wallet A with limit 0
But now Wallet A still has it's limit at 1000
This PR will provide step 4:
4. Wallet A matches Trustline `limit_peer` to 0 so that trustline can be defaulted (severed).
5. Voila, you can delete Wallet A!!!!
> fix(web-client): set trustline limit to 0 if limit_peer is 0

- web-client/src/app/views/wallet/wallet.page.html
- web-client/src/app/views/wallet/wallet.page.ts
This fix hide the "Verify Profile" menu item if the wallet was already verified
> fix(web-client): hide verify menu if already done

- web-client/src/app/components/balance-summary-card/balance-summary-card.component.html
- web-client/src/app/components/balance-summary-card/balance-summary-card.component.ts
Check the wallet's initial balance (XRP) before showing the opt-in option.
The minimum is set to 0.01 which should be enough for the opt-in fee
> fix(web-client): optin only if wallet has xrp

- web-client/src/schema/crypto.ts
- web-client/src/schema/session.ts
- web-server/sgx-wallet-impl/src/schema/mod.rs
- web-server/sgx-wallet-impl/src/schema/session.rs
- web-server/sgx-wallet-test/enclave/Cargo.lock
Certain multi-step wallet operations require that two or more messages related messages be sent for processing by the enclave.   Since the enclave has no built-in means of verifying that such messages are indeed from the same source, a cryptographic mechanism is necessary to essentially establish "sessions" across such messages.
Provide a simple, albeit rudimentary, solution to the aforementioned problem through the use of a combination of a Diffie-Hellman key exchange and session keys deterministically generated by the enclave.
The need for this functionality arose in the context of PR #324, where authentication details need to be verified prior to a follow-up message that contains the new to-be PIN for the user wallet.  The enclave needs some mechanism by which it can verify that the …
> feat: initial wallet enclave sessions

- asset-services/Dockerfile
- asset-services/asset-services-api/Cargo.toml
- asset-services/asset-services-celery/Cargo.toml
- asset-services/asset-services-worker/Cargo.toml
- asset-services/onfido/Cargo.toml
- asset-services/rust-toolchain.toml
- asset-services/twilio-api/Cargo.toml
- asset-services/twilio-verify/Cargo.toml
Bumping rust edition to 2021.
```
If you are trying to migrate from the previous edition (2018), the
process requires following these steps:
1. Start with `edition = "2018"` in `Cargo.toml`
2. Run `cargo fix --edition`
3. Modify `Cargo.toml` to set `edition = "2021"`
4. Run `cargo build` or `cargo test` to verify the fixes worked
More details may be found at
https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html
```
Was trying to use https://crates.io/crates/azure_data_cosmos crate but it was failing to build due to:
```
error: failed to download `time v0.3.14`
Caused by:
unable to get packages from source
Caused by:
failed to parse manifest at `/home/bill/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.3.14/Cargo.toml`
Caused by: …
```
> build(asset-services): update Rust edition to 2021

- web-client/src/app/views/register/register.page.html
The register page would cut the form and not allow user to see other fields when the height get smaller.
The overflow allows the user to scroll to reveal the rest of the form
> Fix-swiper-overflow

- web-server/Dockerfile
- web-server/README.md
`bindgen` recently split out their cli-tool and the library into two parts.
This is causing our web-server tests to fail.
> fix(web-server): update command 'bindgen' to 'bindgen-cli'

- web-client/src/environments/environment.bhutan-prod.ts
- web-client/src/environments/environment.bhutan-staging.ts
- web-client/src/environments/environment.palau-prod.ts
- web-client/src/environments/environment.palau-staging.ts
- web-client/src/environments/environment.prod.ts
- web-client/src/environments/environment.staging.ts
The environment should point to TCP port 51233 as per the [XRPL documentation](https://xrpl.org/xrp-testnet-faucet.html)
> fix(xrpl-client): specify destination port

- web-client/src/app/components/balance-summary-card/balance-summary-card.component.html
Hide entire item that leaves unnecessary space when hiding xrp
> fix(web-client): hide whole item instead of label

- web-client/src/schema/crypto.ts
- web-client/src/schema/session.ts
The client public key was previously unobtainable by the caller.
> refactor(client): expose client public key

- web-client/src/app/state/session.query.ts
- web-client/src/app/views/pull/pull.page.html
- web-client/src/app/views/pull/pull.page.ts
I added a filter on XRP to hide XRP in session.query for pull payments.
This caused a bug where the asset-cordion component for Opting in tokens disappeared.
I removed the filter and filtered the XRP on the pull payment page instead.
> fix(web-client): remove filter of xrp in session query to show opt in

- backend-services/src/data_service/operations/dispatch.py
- backend-services/tests/data_service/operations/test_bookmark.py
Incorrect object passed to the `pydantic` model parser in various instances
> fix(backend-services): incorrect argument

- web-client/src/app/views/wallet/wallet.page.ts
Two changes on Wallet Page:
* Change "Receive" to "My Wallet Address"
* Swap "Receive" with "Pull Payment" button
After:
Before:
> refactor(web-client): modify wallet page buttons

- web-client/src/app/views/pull/pull.page.html
- web-client/src/app/views/pull/pull.page.ts
Small bug from Pull Payments:
When `hideXrpBalance` is `true` and user has no trustline created to the tokenIssuer for the tokenSymbol, the pull page must either not show or display message like the pay page because you cannot receive FOO if you do not have trustline established.
> fix(web-client): show opt in message on pull page

- backend-services/tests/data_service/operations/test_bookmark.py
Mocking the client is unnecessary since it is only used to return a (mock) collection.  Regardless, mocks should always appear before the first instance of the object being mocked.
> refactor(backend/tests): remove superfluous mocks

- web-client/src/app/state/session.service.ts
- web-client/src/schema/actions.ts
- With the current implementation, the user's answers to  security questions are not saved correctly as the JavaScript message pack library does not seem to support ES6 Maps. More details of this issue can be found on this [link](https://github.com/msgpack/msgpack-javascript/issues/138).
- To fix this issue, the auth_map's type is converted (from a Map<string, string> type) to a Object type.
> fix(web-client): Change auth_map type to Object type.

- backend-services/src/web_asgi/main.py
As requested, let the CORS policy allow connections from `localhost:4200` on our staging environment
> fix(cors): allow `localhost:4200` on staging

- web-client/src/app/components/pin-entry/pin-entry.component.html
- web-client/src/app/components/pin-entry/pin-entry.component.ts
- web-client/src/app/views/pull/pull.page.html
- web-client/src/app/views/wallet-access/wallet-access.page.html
Fix: Update pin entry heading when pull payment is about to be initiated.
> fix(web-client): Update Pin Entry text for pull payment.

- backend-services/Dockerfile
- backend-services/poetry.lock
- backend-services/pyproject.toml
Bump `fastapi` to the latest release and track the latest patch for `python3.10` in our image build.
> chore: update fastapi and python

- backend-services/src/data_service/operations/autofund.py
Some successful transactions aren't found right away so it throws an error. This differentiates from other HTTPExceptoins.
> fix (backend-services) fix errors for XRPL exception

- web-client/src/app/components/pin-entry/pin-entry.component.ts
- web-client/src/app/components/quick-access/quick-access.component.ts
When user clicks on ""remember address"", once pin entered, the wallet requests user to enter a nickname and press Ok. If users changes his mind and hits cancel, the wallet is still saved with nickname ""undefined"". In this case, it not only creates an Unknown item in the saved addresses list but duplicates the last entry in the existing saved addresses list where ones already exist. Lastly it allows users to save addresses they already have in their saved addresses which causes confusion and long duplicate lists in the saved addresses.
Current functionality for the removal of saved addresses is to only click the red bin icon on the entry - and it is instantly removed. This can be done far too easily by mistake on a mobile phone, either as the user navigates the screen or tries to copy …
> Fix remember address issue & a confirmation dialog box before removing a saved address 

- web-client/src/app/state/qAccess/q-access.service.ts
- web-client/src/app/views/wallet-access/wallet-access.page.ts
The enter Wallet Nickname dialog box appears on clicking Confirm on the PIN screen, the user then clicks on the text box and starts entering a name and as the app progresses in the background the text box loses focus so the user typing does not work. Note that this is very awkward in Palau where the lag due to internet is much longer (it all happens over many seconds as opposed to 1-2 seconds).
Wait for the wallet nickname to be entered before opening the app
Prevent the same wallet from being saved twice. If the wallet address already exists in local storage do not display the save address checkbox to the user again
> refactor(web-client): nickname prompt before login

- backend-services/src/web_asgi/main.py
The endpoint for creating `OtpRecipientTrigger` documents in the DB was left out of a previous PR.
> feat(backend-services): add forgotten endpoint

- backend-services/Dockerfile
- backend-services/poetry.lock
- backend-services/pyproject.toml
Update some of our dependencies to their latest SemVer compatible version.  FastAPI is updated to the latest version and our Python version is bumped to 3.11.
> chore(backend-services): update dependencies

- backend-services/src/auth_service/operations/twilio_2fa.py
The synchronous API was erroneously being called instead of the asynchronous one
> fix(backend-services): use the async API instead

- backend-services/src/auth_service/operations/twilio_2fa.py
From staging backend-services logs container:
```
[2023-05-22 15:30:43 +0000] [11] [ERROR] Exception in ASGI application Traceback (most recent call last): File "/home/user/.cache/pypoetry/virtualenvs/wallet-backend-services-ydm62z-a-py3.11/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi result = await app( # type: ignore[func-returns-value] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/user/.cache/pypoetry/virtualenvs/wallet-backend-services-ydm62z-a-py3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__ return await self.app(scope, receive, send) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/user/.cache/pypoetry/virtualenvs/wallet-backend-services-ydm62z-a-py3.11/lib/python3.11/site-pack …
```
> fix(backend-services): set correct event loop for OTP Twilio async call

- backend-services/src/auth_service/operations/twilio_2fa.py
- backend-services/src/web_asgi/main.py
Fix did not work:
https://github.com/ntls-io/nautilus-wallet/pull/567/files
From https://www.twilio.com/blog/send-sms-fastapi-twilio:
```
The problem is that the Twilio helper library for Python does not support asynchronous applications. Since this library will be making network requests to Twilio servers, it will block the loop if used directly in the asynchronous function. To avoid this problem, we’ll encapsulate all the Twilio related work in a function that we’ll call send_sms(), and we’ll execute this function inside an [executor](https://docs.python.org/3/library/asyncio-eventloop.html#executing-code-in-thread-or-process-pools) to keep the async application running smoothly.
```
From https://www.twilio.com/blog/twilio-python-helper-library-async:
Using Solution #3 - Using a thread …
> fix(backend-services): use sync Twilio API call in executor

- backend-services/src/web_asgi/main.py
Allow PUT requests from frontend for CORS policy.
For /otp/limit/set - https://github.com/ntls-io/nautilus-wallet/blob/ec9ebb756a826d5e2f696fb0337b9fd94c15aa40/backend-services/src/web_asgi/main.py#L123-L125
> fix(backend-services): allow put requests for CORS policy

- backend-services/src/data_service/operations/otp.py
Update set_otp_limit_trigger() function to first check if a limit exists for a given wallet_id and currency_code. If so, update limit. If not, create a new limit theshold.
> fix(backend): Update set_otp_limit_trigger() function

- backend-services/src/data_service/operations/otp.py
Update create_otp_recipient_trigger() function:
* If there is already a document with the wallet_id and recipient, do nothing - to avoid duplicate document entries.
> fix(backend-services): update create_otp_recipient_trigger function

- web-server/README.md
Follow up on https://github.com/ntls-io/nautilus-wallet/pull/517/files, for builds without Docker, need to update README as well.
> docs(web-server): pin 'bindgen-cli' version to 0.63.0

- web-server/Dockerfile
- web-server/README.md
Github action workflows were failing due to:
```
~/workspace/nautilus-wallet/web-server/sgx-wallet fix-backend-pin-reset ❯ cargo install --version 0.63.0 bindgen-cli                                                   15:17:19
Updating crates.io index
Installing bindgen-cli v0.63.0
Downloaded which v4.4.0
Downloaded libloading v0.7.4
Downloaded glob v0.3.1
Downloaded log v0.4.19
Downloaded env_logger v0.9.3
Downloaded proc-macro2 v1.0.60
Downloaded clang-sys v1.6.1
Downloaded bindgen v0.63.0
Downloaded libc v0.2.146
Downloaded os_str_bytes v6.5.1
Downloaded 10 crates (1.1 MB) in 0.77s
error: failed to compile `bindgen-cli v0.63.0`, intermediate artifacts can be found at `/tmp/cargo-installwYOz0D`
Caused by:
package `log v0.4.19` cannot be built because it requires rustc 1.60.0 or newer, …
```
> fix(web-server): add --locked flag to bindgen-cli install command

- web-client/src/app/components/new-bookmark/new-bookmark.component.ts
- web-client/src/app/utils/notification/swal-helper.ts
- web-client/src/app/utils/validators.ts
- web-client/src/app/views/triggers/triggers.page.ts
The aim of this PR is to resolve the following issue: [PAY: Unsupported Address Screen](https://ntls.atlassian.net/jira/software/projects/NW/boards/1?selectedIssue=NW-205).
A wallet address is first checked for its validity before saving a new bookmark. That way, any payments made via bookmarks page will consist of valid addresses.
> fix(web-client): wallet address validator for bookmark.

- backend-services/src/data_service/operations/recurringpayment.py
- backend-services/src/data_service/schema/actions.py
- backend-services/src/data_service/schema/entities.py
- backend-services/src/web_asgi/main.py
Initial implementation of recurring payments APIs for cosmosDB.
<meta charset="utf-8"><h1 dir="ltr" style="line-height:1.38;margin-top:20pt;margin-bottom:6pt;" id="docs-internal-guid-39945dd5-7fff-b1c1-5bc4-ffd9529ca055"><span style="font-size:20pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Database Schema - Recurring Payment</span></h1><br /><div dir="ltr" style="margin-left:0pt;" align="left">
Field | Type
-- | --
wallet_id | string
wallet_public_key | string
recipient | string
amount | float
currency_code | string
payment_start_date | integer (UNIX epoch)
frequency | days
payment_end_date| Integer (UNIX epoch)
</div>
GET | …
> feat(backend-services): add recurring payments implementation

- web-server/sgx-wallet-impl/src/schema/actions.rs
- web-server/sgx-wallet-impl/src/wallet_operations/dispatch.rs
- web-server/sgx-wallet-impl/src/wallet_operations/mod.rs
- web-server/sgx-wallet-impl/src/wallet_operations/sign_transaction_recurring_payment.rs
- web-server/sgx-wallet-impl/src/wallet_operations/store.rs
- web-server/sgx-wallet-test/enclave/src/lib.rs
- web-server/sgx-wallet-test/enclave/src/wallet_operations/mod.rs
- web-server/sgx-wallet-test/enclave/src/wallet_operations/test_sign_transaction_recurring_payment.rs
For Recurring Payments, need an endpoint to sign XRPL transactions for Nautilus Wallet without users pin.
NB!!
Need to revert this PR after testing.
> feat(web-server): add sign_transaction_recurring_payment operation

- backend-services/src/data_service/operations/recurringpayment.py
- backend-services/src/data_service/schema/actions.py
- backend-services/src/data_service/schema/entities.py
- backend-services/src/web_asgi/main.py
- web-client/src/app/app-routing.module.ts
- web-client/src/app/components/new-schedule-pay/new-schedule-pay.component.html
- web-client/src/app/components/new-schedule-pay/new-schedule-pay.component.spec.ts
- web-client/src/app/components/new-schedule-pay/new-schedule-pay.component.ts
- web-client/src/app/components/new-schedule-pay/new-schedule-pay.module.ts
- web-client/src/app/state/recurring-pay/index.ts
- web-client/src/app/state/recurring-pay/recurring-pay.model.ts
- web-client/src/app/state/recurring-pay/recurring-pay.query.ts
- web-client/src/app/state/recurring-pay/recurring-pay.service.ts
- web-client/src/app/state/recurring-pay/recurring-pay.store.ts
- web-client/src/app/views/recurring-pay/recurring-pay-routing.module.ts
- web-client/src/app/views/recurring-pay/recurring-pay.module.ts
- web-client/src/app/views/recurring-pay/recurring-pay.page.html
- web-client/src/app/views/recurring-pay/recurring-pay.page.spec.ts
- web-client/src/app/views/recurring-pay/recurring-pay.page.ts
- web-client/src/app/views/schedule-pay/schedule-pay-routing.module.ts
- web-client/src/app/views/schedule-pay/schedule-pay.module.ts
- web-client/src/app/views/schedule-pay/schedule-pay.page.html
- web-client/src/app/views/schedule-pay/schedule-pay.page.spec.ts
- web-client/src/app/views/schedule-pay/schedule-pay.page.ts
- web-client/src/app/views/wallet/wallet.page.ts
Implementation of Frontend Recurring Payment feature.
> feat(web-client): Recurring payments feature.

- web-client/src/app/components/bookmark-list/bookmark-list.component.html
- web-client/src/app/components/bookmark-list/bookmark-list.component.ts
This PR aims to solve the following ticket: [NW-134: As a wallet holder I want to be able to make payments directly from my Bookmarks so that I do not have to do too many steps](https://ntls.atlassian.net/jira/software/projects/NW/boards/1?selectedIssue=NW-134)
Acceptance Criteria:
- The user can see 2 options/buttons on the bookmark: Send Payment & Pull Payment
- They are taken directly to the payment page without needing to copy and paste an address
> refactor(web-client): payments via bookmark.

- web-client/src/app/utils/notification/swal-helper.ts
- web-client/src/app/views/deposit-funds/deposit-funds.page.ts
- web-client/src/app/views/pay/pay.page.ts
- web-client/src/app/views/pull/pull.page.ts
Improve ripple-related transaction error messages for the user. This PR addresses issues: [NW-107](https://ntls.atlassian.net/jira/software/projects/NW/boards/1?selectedIssue=NW-107) &  [NW-219](https://ntls.atlassian.net/jira/software/projects/NW/boards/1?selectedIssue=NW-219)
1. Sending funds to a deleted wallet.
When user tries to send funds to a deleted wallet, a notification should popup, informing the user that they cannot send funds to a wallet that has been deleted.
2. Pulling funds from a deleted wallet.
When user attempts to pull funds wallet from a deleted wallet; a notification should let them know that they should not be able to do so.
3. Pulling funds from a wallet that has insufficient tokens or has not opted into the currency.
When user attempts to pull funds wallet from a …
> refactor(web-client): improve error messages.

- web-client/src/global.scss
- web-client/src/theme/variables.scss
Aim of this PR is to address the following issue: [Unable to read input text on country code form](https://ntls.atlassian.net/jira/software/projects/NW/boards/1?selectedIssue=NW-179)
> fix(web-client): Fix phone input colors.

- web-server/sgx-wallet-impl/src/lib.rs
- web-server/sgx-wallet-impl/src/schema/actions.rs
- web-server/sgx-wallet-impl/src/schema/entities.rs
- web-server/sgx-wallet-impl/src/wallet_operations/create_wallet.rs
- web-server/sgx-wallet-impl/src/wallet_operations/open_wallet.rs
- web-server/sgx-wallet-impl/src/wallet_operations/pin_reset.rs
- web-server/sgx-wallet-impl/src/wallet_operations/store.rs
- web-server/sgx-wallet-impl/src/wallet_operations/update_otp_number.rs
https://ntls.atlassian.net/browse/NW-203?atlOrigin=eyJpIjoiZDg2Y2U1YjY1N2FiNGQ1ZGFkMDYxYmYxNDFhZjMxMzUiLCJwIjoiaiJ9
New feature to lock account if there are 3 attempts to log into account with incorrect pin.
This PR is for the Nautilus Wallet backend web-server.
Implementation plan:
web-server:
* add account_attempts: u32 to WalletStorable
* when open_wallet is called, increase account_attempts  by 1 if open_wallet fails for incorrect pin
* when open_wallet succeeds, reset account_attempts to 0
* when create_wallet is called for new wallet initialize account_attempts to 0
* for existing accounts, if account_attempts is none, or not there, add it to WalletStorable when open_wallet is called
* when open_wallet is called and account_attempts is equal to 3 or greater (should not be possible), …
> feat(web-server): initial implementation for account lock

- web-client/src/app/services/auto-logout.service.ts
- web-client/src/app/views/pay/pay.page.ts
- web-client/src/app/views/pull/pull.page.ts
Aim of this PR is to disable Auto Logout when user is confirming transactions (for pull and pay payments).
> fix(web-client): diasble autologout in send & pull pay

- web-client/src/app/state/session.service.ts
- web-client/src/schema/actions.ts
If the backend returns Account Locked error when unlocking a wallet, display appropriate error.
https://ntls.atlassian.net/browse/NW-203
> feat(web-client): add error handling for account locked
